server:
  port: 8081

spring:
  datasource:
    batch:
      url: jdbc:mysql://localhost:3306/batch
      username: root
      password: test

    streaming:
      url: jdbc:mysql://localhost:3306/streaming
      username: root
      password: test

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always